//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\benjy\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://slicedbreaddevelopment.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /generateActions /out:"C:\Users\benjy\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\Actions.cs" /namespace:"SB.CRM" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"ben.evans@slicedbread.co.uk" /password:"********" 
//------------------------------------------------------------------------------

namespace SB.CRM
{
	
}
